sonar.projectKey=boardgame-devsecops
sonar.projectName=Board Game DevSecOps
sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**,monitoring/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
