apiVersion: apps/v1
kind: Deployment

metadata:
  name: boardgame-api
  namespace: boardgame

spec:
  replicas: 2

  selector:
    matchLabels:
      app: boardgame-api

  template:

    metadata:
      labels:
        app: boardgame-api

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"

    spec:

      # Kubernetes restricted PodSecurity
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001

        # IMPORTANT FIX
        seccompProfile:
          type: RuntimeDefault

      containers:

        - name: boardgame-api

          image: IMAGE_PLACEHOLDER

          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          securityContext:
            allowPrivilegeEscalation: false

            capabilities:
              drop:
                - ALL

          resources:

            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 256Mi

          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP

            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP

            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5
